version: '3'
services:
    api:
        build: ./api
        container_name: chat-app-api
        ports: 
            - 9000:9000
        # links: 
        #     - chat-app-client

    client:
        build: ./client
        container_name: chat-app-client
        ports: 
            - 8080:8080
        # links: 
        #     - chat-app-api